[toolchain]
anchor_version = "0.31.0"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
svm_evm_demo = "8ytSoUuPamxUoYs8YTkV1tdnhQAHHbyjB3DWJHTVzRBd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/svm-evm-demo.ts"
